//anaconda3/lib/python3.7/site-packages/segway/observations.py:435: RuntimeWarning: invalid value encountered in arcsinh
  float_data = arcsinh(float_data)
